# Generated by Django 6.1 on 2026-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_key', models.CharField(blank=True, max_length=255, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_dividend_value', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('last_dividend_date', models.BigIntegerField(blank=True, null=True)),
                ('dividend_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('dividends', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
