# Generated by Django 6.1 on 2026-09-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dividend_remove_stock_dividends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='most_recent_quarter',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
